### ISSUE TITLE
Can we make nested methods work

### ISSUE THREAD

**Issue by aerni** [Stillat/primitives#2]
This works like a charm! What about nested methods? Is this something that could be supported as well?

```php
randomElements(['a', 'b', 'c', 'd', 'e'], rand(1, 5))
```

**Comment by aerni** [comment]
The following code is returning an error `Unknown format "rand"`. I suppose it's because `rand()` is a basic PHP method and doesn't exist in the Faker class. Is there a way to make this work?

```php
$parser = new Parser();
$runner = new MethodRunner();

$methods = $parser->parseMethods("randomElements(['a', 'b', 'c', 'd', 'e'], rand(1, 5))");
$result = $runner->run($methods, $this->faker);
```

**Comment by JohnathonKoster** [comment]
To add to core, there would need to be a lot of thought into which methods are considered "safe" - and those opinions will always differ. To accomplish this, we can create a class that will sit inbetween the method runner and the faker instance, and make heavy use of the `__call` magic method to decide if we should call a native PHP function or one on the instance:

```php
<?php

use Stillat\Primitives\Parser;
use Stillat\Primitives\MethodRunner;

$parser = new Parser();
$runner = new MethodRunner();

class Greeter {

    public function sayHello($name)
    {
        return 'Hello, '.$name;
    }

}

class MethodTarget
{

    protected $instance;
    protected $safePhpFunctions = [
        'strtoupper'
    ];

    public function __construct()
    {
        $this->instance = new Greeter();
    }

    public function __call($name, $arguments)
    {
        // Replace with whatever logic makes sense. This approach
        // utilizes an allowed list of functions, but using
        // something like function_exists also works.
        if (in_array($name, $this->safePhpFunctions)) {
            return call_user_func($name, ...$arguments);
        }

        return call_user_func([$this->instance, $name], ...$arguments);
    }

}

$instance = new MethodTarget();

$result = $parser->parseMethods('sayHello(strtoupper("this is lowercase"))');

$methodResult = $runner->run($result, $instance);
```

After the above code has executed, `$methodResult` would contain `Hello, THIS IS LOWERCASE`.

**Comment by aerni** [comment]
Yeah, makes sense. I didn't think too much about security concerns. Thanks!
